Repository MoneyMakersClub/mmc-backend, pull requests merged in 2024-11, with the labels that each got.

#30 [Fix] 소셜 로그인 성공 시 전달하는 쿼리파라미터 추가
  bookduck/src/main/java/com/mmc/bookduck/global/oauth2/CustomOAuth2UserService.java
  bookduck/src/main/java/com/mmc/bookduck/global/oauth2/OAuth2Attributes.java
  bookduck/src/main/java/com/mmc/bookduck/global/oauth2/OAuth2SuccessHandler.java
  bookduck/src/main/java/com/mmc/bookduck/global/oauth2/OAuth2UserDetails.java
  bookduck/src/main/java/com/mmc/bookduck/global/security/JwtUtil.java
Labels: enhancement

#32 [Feat] OCR인식, 발췌 저장 기능
  bookduck/build.gradle
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/controller/ExcerptController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/dto/request/ExcerptCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/dto/response/ExcerptResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/service/ExcerptService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/service/OcrService.java
  bookduck/src/main/java/com/mmc/bookduck/global/exception/ErrorCode.java
  bookduck/src/main/java/com/mmc/bookduck/global/google/GoogleCloudUploadService.java
Labels: enhancement

#46 [Feat] 기록 통합생성, 발췌 조회(archiveId가 있으면 감상평도 함께 조회), 감상평 조회(archiveId가 있으면 발췌도 함께 조회)
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/controller/ArchiveController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ArchiveCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ExcerptCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ReviewCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ArchiveResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ExcerptResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ReviewResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Archive.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Excerpt.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Review.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ArchiveRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ExcerptRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ReviewRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ExcerptService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/OcrService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ReviewService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/repository/UserBookRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/controller/ExcerptController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/dto/request/ExcerptCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/repository/ExcerptRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/excerpt/service/ExcerptService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/review/repository/ReviewRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/user/controller/UserController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/user/service/UserGrowthService.java
  bookduck/src/main/java/com/mmc/bookduck/global/common/BaseTimeEntity.java
Labels: enhancement

#55 [Fix] 친구/친구요청 응답 dto 구성 수정
  bookduck/src/main/java/com/mmc/bookduck/domain/friend/dto/common/FriendRequestUnitDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/friend/dto/response/FriendListResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/friend/service/FriendRequestService.java
Labels: fix

#57 [Fix] archive 생성, 조회 기능
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/controller/ArchiveController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ArchiveCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ExcerptCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ReviewCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ArchiveResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ExcerptResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ReviewResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/ArchiveType.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ExcerptRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ReviewRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ExcerptService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ReviewService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
  bookduck/src/main/java/com/mmc/bookduck/global/exception/ErrorCode.java
  bookduck/src/main/java/com/mmc/bookduck/global/exception/GlobalExceptionHandler.java
Labels: fix

#77 [Feat] Archive 통합 수정, 삭제 기능 API
  .github/workflows/github-action.yml
  bookduck/Dockerfile
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/controller/ArchiveController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ArchiveUpdateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ExcerptCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ExcerptUpdateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ReviewCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ReviewUpdateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Archive.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Excerpt.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Review.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ExcerptService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ReviewService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/folder/service/FolderService.java
  bookduck/src/main/java/com/mmc/bookduck/global/config/GoogleCloudConfig.java
  bookduck/src/main/java/com/mmc/bookduck/global/google/GoogleCloudUploadService.java
Labels: enhancement

#93 [Feat] 한줄평 생성, 수정, 삭제, 좋아요, 좋아요취소, 한줄평/별점 목록 조회 기능 개발
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/controller/ArchiveController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/request/ExcerptCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ArchiveResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Excerpt.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/Review.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ExcerptService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/BookInfoController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/service/BookInfoService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/service/UserBookService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/controller/OneLineController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/dto/request/OneLineCreateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/dto/request/OneLineUpdateRequestDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/dto/response/OneLineRatingListResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/dto/response/OneLineRatingUnitDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/entity/OneLine.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/repository/OneLineRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/service/OneLineService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/onelineLike/repository/OneLineLikeRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/onelineLike/service/OneLineLikeService.java
  bookduck/src/main/java/com/mmc/bookduck/global/exception/ErrorCode.java
Labels: enhancement

#112 [Feat] 유저 기록 아카이브 조회 - 전체, 발췌만, 감상평만
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ReviewResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/UserArchiveResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/entity/ArchiveType.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ExcerptRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ReviewRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/friend/dto/common/FriendUnitDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/friend/repository/FriendRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/friend/service/FriendService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/service/OneLineService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/user/controller/UserController.java
  bookduck/src/main/java/com/mmc/bookduck/global/exception/ErrorCode.java
Labels: enhancement

#140 [Feat] 캐릭터/통계 요약 내보내기 정보 제공 기능 개발
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ExcerptRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ReviewRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/repository/UserBookRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/export/controller/ExportController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/export/dto/ExportCharResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/export/dto/ExportStatsResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/export/service/ExportService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/controller/OneLineController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/oneline/dto/response/OneLineRatingUnitDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/user/controller/UserController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/user/dto/response/UserKeywordResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/user/service/UserReadingReportService.java
Labels: enhancement, fix

#150 [Feat] 기록 검색 기능 구현
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/controller/ArchiveController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/common/ExcerptSearchUnitDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/common/ReviewSearchUnitDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ArchiveSearchListResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/UserArchiveResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ArchiveRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/controller/BookInfoController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/service/BookInfoService.java
Labels: enhancement

#158 [Feat] 공유된 링크로 발췌 및 감상평 통합 조회 기능 개발
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/controller/ArchiveController.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/global/config/SecurityConfig.java
Labels: enhancement

#182 [Fix] 기록 검색 dto 구조 수정, 책제목으로도 검색 가능하게 수정
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/ArchiveSearchListResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/dto/response/UserArchiveResponseDto.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/repository/ArchiveRepository.java
  bookduck/src/main/java/com/mmc/bookduck/domain/archive/service/ArchiveService.java
  bookduck/src/main/java/com/mmc/bookduck/domain/book/service/BookInfoService.java
Labels: fix
